name: Build Node.js 10 ARM64 Docker Image

on:
  workflow_dispatch: # Permite ejecutar manualmente desde la UI de GitHub
  schedule:
    - cron: "0 0 * * 1" # Ejecutar todos los lunes a la medianoche (UTC)
  push:
    branches:
      - master
    paths:
      - nodejs/10/** # Solo se ejecutará si se modifican archivos dentro de nodejs/10/

jobs:
  build:
    name: "Build Node.js 10 ARM64 Docker Image"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 10  # Solo Node.js 10 para ARM64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Configuración de QEMU para permitir la construcción de imágenes ARM64
      - name: Setup QEMU for ARM64 Build
        uses: docker/setup-qemu-action@v3

      # Configuración de Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      # Login en GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}  # Usar el token almacenado en los secretos

      # Construcción y envío de la imagen Docker para Node.js 10 ARM64
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./nodejs/10
          file: ./nodejs/10/Dockerfile  # Ruta del Dockerfile para Node.js 10
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner | downcase }}/yolks:nodejs_10_arm64
